# Import libraries

In [ ]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Read dataset

In [3]:
# Read csv using Pandas
dataset = pd.read_csv('Data.csv')

In [4]:
# Dataset head
dataset.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [5]:
# Dataset tail
dataset.tail()

   Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

# Creating features and target

In [6]:
# Split X and y
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [7]:
# Check X
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [8]:
# Check y
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

# handling missing values

In [9]:
# Checking for the missing values
dataset.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [10]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\windows\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\windows\anaconda3\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in c:\users\windows\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\windows\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\windows\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import sklearn

In [12]:
# Impute missing values
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.fit_transform(x[:,1:3])

In [13]:
# Check X
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Encoding categorical variable

In [14]:
# Encode categorical data
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[0])], remainder='passthrough')
x= np.array(ct.fit_transform(x))

In [15]:
# Check X
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

# Encode target variable

In [ ]:
# Encode target variable y
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [17]:
# Check y
print(y_encoded)

[0 1 0 0 1 1 0 1 0 1]

# Train test split

In [18]:
# Split dataset into training set and testing set
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [20]:
# Check X_train
x_train

array([[1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0]], dtype=object)

In [21]:
# Check X_test
x_test

array([[0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0]], dtype=object)

In [22]:
# Check y_train
y_train

array(['Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No'], dtype=object)

In [23]:
# Check y_test
y_test

array(['No', 'Yes'], dtype=object)

# Feature scaling

In [24]:
# Feature scaling

In [30]:
# Transform X_test into same scale
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

#Standersization
# from sklearn.preprocessing import StandardScaler

# sc = StandardScalar()
# x_train[:,3:] = sc.fit_transform(x_train[:,3:]
# x_test[:,3:] = sc.transform(x_test[:,3:])

In [27]:
# Check X_test
x_test

array([[ 0.        ,  1.        ,  0.        ,  1.11111111,  1.14814815],
       [ 0.        ,  0.        ,  1.        , -0.16666667, -0.14814815]])

In [28]:
# Check X_train
x_train

array([[1.        , 0.        , 0.        , 0.27777778, 0.22222222],
       [1.        , 0.        , 0.        , 0.77777778, 0.74074074],
       [1.        , 0.        , 0.        , 1.        , 1.        ],
       [0.        , 1.        , 0.        , 0.        , 0.07407407],
       [1.        , 0.        , 0.        , 0.38888889, 0.55555556],
       [0.        , 1.        , 0.        , 0.55555556, 0.43621399],
       [0.        , 0.        , 1.        , 0.44444444, 0.33333333],
       [0.        , 0.        , 1.        , 0.48765432, 0.        ]])